# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d6bbf47dabe7418f9ad3a8ad7bbccac"
name = "Viet An Express"
application_url = "https://vietan-express.vercel.app/api/v1/ecom/shopify/launch"
embedded = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "https://vietan-express.vercel.app/api/v1/ecom/webhooks/shopify"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  topics = [ "app/uninstalled", "orders/create", "orders/updated" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://vietan-express.vercel.app/api/v1/ecom/oauth/shopify/callback"
]
