// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VietAnExpress.Ecommerce.Infrastructure;

#nullable disable

namespace VietAnExpress.Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ecommerce")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VietAnExpress.Ecommerce.Domain.SalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Kieu_Ket_Noi");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma_Kenh");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Dang_Hoat_Dong");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten_Kenh");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("Thu_Tu");

                    b.Property<bool>("SupportsTrackingPush")
                        .HasColumnType("bit")
                        .HasColumnName("Day_Tracking");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Website");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code")
                        .HasName("AK_KenhTMDT_Ma_Kenh");

                    b.ToTable("KenhTMDT", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthType = "oauth2",
                            Code = "shopify",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Shopify",
                            SortOrder = 1,
                            SupportsTrackingPush = true,
                            Website = "https://www.shopify.com"
                        },
                        new
                        {
                            Id = 2,
                            AuthType = "oauth2",
                            Code = "tiktok",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "TikTok Shop",
                            SortOrder = 2,
                            SupportsTrackingPush = true,
                            Website = "https://seller.tiktokshop.com"
                        },
                        new
                        {
                            Id = 3,
                            AuthType = "oauth2",
                            Code = "amazon",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Amazon",
                            SortOrder = 3,
                            SupportsTrackingPush = true,
                            Website = "https://sellercentral.amazon.com"
                        },
                        new
                        {
                            Id = 4,
                            AuthType = "oauth2",
                            Code = "ebay",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "eBay",
                            SortOrder = 4,
                            SupportsTrackingPush = true,
                            Website = "https://www.ebay.com"
                        },
                        new
                        {
                            Id = 5,
                            AuthType = "oauth2",
                            Code = "etsy",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Etsy",
                            SortOrder = 5,
                            SupportsTrackingPush = true,
                            Website = "https://www.etsy.com"
                        },
                        new
                        {
                            Id = 6,
                            AuthType = "api_key",
                            Code = "woocommerce",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "WooCommerce",
                            SortOrder = 6,
                            SupportsTrackingPush = true,
                            Website = "https://woocommerce.com"
                        },
                        new
                        {
                            Id = 7,
                            AuthType = "oauth2",
                            Code = "shopee",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Shopee",
                            SortOrder = 7,
                            SupportsTrackingPush = false,
                            Website = "https://banhang.shopee.vn"
                        },
                        new
                        {
                            Id = 8,
                            AuthType = "oauth2",
                            Code = "lazada",
                            CreateDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Lazada",
                            SortOrder = 8,
                            SupportsTrackingPush = false,
                            Website = "https://sellercenter.lazada.vn"
                        });
                });

            modelBuilder.Entity("VietAnExpress.Ecommerce.Domain.StoreConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessTokenEncrypted")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Access_Token_Ma_Hoa");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Access_Token_Het_Han");

                    b.Property<string>("ChannelCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma_Kenh");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Ngay_Ket_Noi");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("Tien_Te")
                        .IsFixedLength();

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Ngay_Ngat_Ket_Noi");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Loi_Gan_Nhat");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Ngay_Loi");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Dong_Bo_Lan_Cuoi");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Refresh_Token_Ma_Hoa");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Refresh_Token_Het_Han");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Khu_Vuc");

                    b.Property<string>("Scopes")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Quyen_Truy_Cap");

                    b.Property<string>("ShopCipher")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Shop_Cipher");

                    b.Property<string>("ShopDomain")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_Mien_Shop");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ma_Shop");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Ten_Shop");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Trang_Thai");

                    b.Property<string>("WebhookIds")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Webhook_IDs");

                    b.HasKey("Id");

                    b.HasIndex("ChannelCode", "ShopId")
                        .HasDatabaseName("IX_KetNoiTMDT_Ma_Kenh_Ma_Shop");

                    b.HasIndex("CustomerId", "ChannelCode", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("UX_KetNoiTMDT_CustomerID_Ma_Kenh_Ma_Shop");

                    b.ToTable("KetNoiTMDT", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_KetNoiTMDT_Trang_Thai", "[Trang_Thai] IN ('active', 'expired', 'error', 'revoked')");
                        });
                });

            modelBuilder.Entity("VietAnExpress.Ecommerce.Domain.StoreConnection", b =>
                {
                    b.HasOne("VietAnExpress.Ecommerce.Domain.SalesChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KetNoiTMDT_KenhTMDT_Ma_Kenh");
                });
#pragma warning restore 612, 618
        }
    }
}
